baseurl = "http://example.com/"
# If you use "hugo server" you might want to use this entry:
#baseurl = "http://localhost:1313/"
title = "Hamburg theme example"
copyright = "&copy; Lorem ipsum ... and so on ..."

theme = "hamburg"

[menu]
	[[menu.main]]
		name = "About"
		identifier = "about"
		url = "pages/about"

[params]
	subtitle = "The great example site of the hugo-hamburg-theme"
	mainSections = ["posts"]
